### ISSUE TITLE
OAuthStorage not inject in DefaultOAuthInterceptor with --prod flag

### ISSUE THREAD

**Issue by alecrt** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#12]
Hi, 

i'm using your module in a angular 7 project and it works fine using dev ng build.

But if I build the angular app with --prod flag I get this.authStorage undefined in default-oauth.interceptor.ts - row 48: 

``` 
       const sendAccessToken = this.moduleConfig.resourceServer.sendAccessToken;
        if (sendAccessToken && this.authStorage.getItem('access_token')) {   <-- ERROR HERE
            const token = this.authStorage.getItem('access_token');
            const header = 'Bearer ' + token;

            const headers = req.headers.set('Authorization', header);

            req = req.clone({ headers });
        }
```

The issue disappear if I remove from core.module.ts
`{ provide: OAuthStorage, useValue: localStorage }`

I'm on Angular 7.0.3.

Thank you,
Alessandro

**Comment by jeroenheijmans** [comment]
We had a short conversation in the library's issue about this as well. I'll repeat my comment here too:

> If I try to:
> 
> 1. Update to the latest master commit of the sample repo
> 1. Do `npm ci` to get latest packages
> 1. Then run `ng build -c production`
> 1. Then run `serve ./dist/sample-auth-guards/ -p 4200`
> 1. Open Chrome latest on Windows 10, go to `http://localhost:4200`, hit "Log in", then log in with user "max", password "geheim", and consent
> 
> Result:
> 
> - I get redirected back to the app, and localStorage is filled with data.
> 
> as expected. 
> 
> So I suspect there's something in your environment, server, or setup that is causing the issue...

Could you please try to add more precise steps and/or environment specifics? Perhaps also try on another fresh environment?

**Comment by alecrt** [comment]
Hi @jeroenheijmans, 

you're not getting the error because you're not calling any protect API in your test project, so you're not firing the DefaultOAuthInterceptor.

Try to modify your ApiService like this
```
@Injectable()
export class ApiService {
  constructor(private authService: OAuthService, private httpClient: HttpClient) { }

  getRandomItem(): Observable<string> {
    if (this.authService.hasValidAccessToken()) {
      console.log('OK! We have a valid access token.');
    } else {
      console.error('ERROR! No valid access token for calling the API.');
    }
    return this.httpClient.get<string>('/api/fake');
  }
}
```
and your OAuthModuleConfig like this to ensure DefaultOAuthInterceptor will get fired
```
import { OAuthModuleConfig } from 'angular-oauth2-oidc';

export const authModuleConfig: OAuthModuleConfig = {
  resourceServer: {
    allowedUrls: ['http://localhost:8080', '/api'],
    sendAccessToken: true,
  }
};
```

**Comment by alecrt** [comment]
Hi @jeroenheijmans,

did you achieved reproducing the issue?

**Comment by jeroenheijmans** [comment]
Sorry, haven't tried your latest suggestion yet. Between Advent of Code and some vacation in the next few weeks it might be a while.

In the mean time, if you feel like delving deeper into this, and looking for a fix, that would certainly be helpful.

**Comment by alecrt** [comment]
Same problem, time is never enough

**Comment by dennisameling** [comment]
The problem is caused by the following snippet:

```TypeScript
export class CoreModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: CoreModule,
      providers: [
       ...
        { provide: OAuthStorage, useValue: localStorage },
      ]
    };
  }
 ...
}
```
Since localStorage does not exist during build time in AOT (e.g. when running `ng build --prod`), it is `undefined` when it's executed by the `angular-oauth2-oidc` library.

Looking at the OAuth2 library, if you don't provide an OAuthStorage like above, `sessionStorage` [will be taken](https://github.com/manfredsteyer/angular-oauth2-oidc/blob/master/projects/lib/src/factories.ts#L5-L7) as default:

```TypeScript
export function createDefaultStorage() {
    return typeof sessionStorage !== 'undefined' ? sessionStorage : null;
}
```

This **does** work, as sessionStorage is only accessed when the function "createDefaultStorage" is ran, so not during build time.

The workaround for now is to remove the snippet `{ provide: OAuthStorage, useValue: localStorage }`, which will default to `sessionStorage`, and a minor refactoring of the OAuthStorage in the OAuth2 library is needed. Will check if I can provide a PR for this in the [angular-oauth2-oidc](https://github.com/manfredsteyer/angular-oauth2-oidc) repo.
