### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by lgoudriaan** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#4]
Hi Jeroen,

Thanks for your sample.

Do you have any clue how to get this working with SSR and lazy loading of modules?
When I add the authservice and authguard to my project the page stays blank with initialNavigation: 'enabled' on the routermodule.

Thanks in advance

ps. can you add a License to this sample?

**Comment by jeroenheijmans** [comment]
@lgoudriaan Thank you for the kind remarks.

With SSR you mean [Angular Universal](https://angular.io/guide/universal), right? I haven't looked into that yet, as my own production case is a backoffice application that does not require most of the features offered by Universal. I'm curious though, so will leave the issue open and see if I can find some time to investigate.

The other one (lazy loading of modules) might be a seperate issue. I have zero issues in my production app that does use lazy loaded feature modules, I might update my example to showcase that as well.

As for the license, I've added #5 as a reminder and will add one somewhere this week. It'll be MIT most likely, though I'd be happy to consider another one if your project requires it.

**Comment by lgoudriaan** [comment]
Thanks for the quick response.

Sorry my title is a little misleading, little more explanation:

With SSR I indeed mean Angular Universal.

To prevent screen flicker with SSR I need to add the RouterModule like this: ```RouterModule.forRoot(routes, { initialNavigation: 'enabled' })```, but with this settings the initial page load stays blank.

**Comment by jeroenheijmans** [comment]
I've added a license in bdc4d55eab04c62b8b94806c4ddd89eaf200a02a (#5), it's MIT so you should be good to go with both open source and proprietary apps.

I've also separated your question on lazy loaded feature modules into #7, since SSR / Angular Universal seems like a separate concern.

I might not get to trying out Angular Universal any time soon though I'm afraid, so this issue might remain open for a bit. Let us know if you ever found out about the specifics. (I'd guess mostly the Storage would give you trouble, apart from the fact that it doesn't make sense to let the server render *any* protected pages since it can never log in on behalf of the user).

**Comment by jeroenheijmans** [comment]
Going to close this for now. I estimate the base example might become too complex (so: I would be happy to _consider_ a PR for this, but might not include it if the basics don't stay clear).

Either way: thanks for the suggestions/interactions.
