### ISSUE TITLE
Login always fails

### ISSUE THREAD

**Issue by scottjohnson0** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#45]
Hi,
I cloned this repo, installed and launched. Every time I click the login button I get

![image](https://user-images.githubusercontent.com/12751608/87429891-6f470f80-c5b2-11ea-9a34-27f79b5c41c1.png)

I **think** that some time ago I cloned this repo and ran the demo and it worked.  Has something changed or maybe I'm doing something wrong? Thanks.

**Comment by jeroenheijmans** [comment]
I presume this is a duplicate of #43. If you cloned it some time ago, your current commit is likely still using Implicit Flow, and this flow was removed from demo.identityserver.io which I rely on with my sample.

**Comment by scottjohnson0** [comment]
@jeroenheijmans Thanks for your reply. I cloned it yesterday and then again just now, into fresh directories.  What I meant above was I think I had tested this a while ago and it worked, and then deleted that repo.
Anyway - I cloned it just now and I see what I reported above.
by the way, I had to delete package-lock.json in order for the install to work - npm gave me this error until i deleted that file

EINTEGRITY
npm ERR! sha1-hX/Kv8M5fSYluCKCYuhqp6ARsF0= integrity checksum failed when using sha1: wanted sha1-hX/Kv8M5fSYluCKCYuhqp6ARsF0= but got sha512-GY8fANSrTMfBVfInqJAY41QkOM+upUTytK1jZ0c8+3HdHrJxBJ3rF5i9moClXTE8uUSnUo8cAsCoxDXvSY4DHg== sha1-gnuk51k0ZOfCIejFvtkwkE7ixFU=. (6958 bytes)

**Comment by Gamewalker** [comment]
freshly downloaded project and the same for me

**Comment by jeroenheijmans** [comment]
I presume the Original Post in this thread is due to the implicit client having been removed from the IDS, and the other issues reported later on are seperate and likely due to a bad recent merge of an automated security update?

Will investigate when I have time...

**Comment by jeroenheijmans** [comment]
Turns out the Code flow client id was also updated in demo.identityserver.io (as is their good right!). I've [updated this for master branch](https://github.com/jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards/commit/3189795daf7757fa9f9cd692c00541993d59ec00), @scottjohnson0 or someone from the thread can you confirm it's working again?

For the issue with package-lock needing to be deleted, please open a fresh issue with a clean way to reproduce it for me. I currently cannot reproduce it so not sure how to fix it...

**Comment by Gamewalker** [comment]
working fine :)

**Comment by scottjohnson0** [comment]
@jeroenheijmans 
Looks good, thanks!
