### ISSUE TITLE
Edge issue: Validating access_token failed, wrong state/nonce

### ISSUE THREAD

**Issue by mores** [jeroenheijmans/sample-angular-oauth2-oidc-with-auth-guards#9]
I am running keycloak with 2 users - 1 local to keycloak and 1 from microsoft azure.

In Chrome - everything is working as expected for both users.

In Edge - local keycloak user is able to login and logout fine.
- microsoft azure - first attempt to login gets invalid_nonce_in_state
  hit the login button a second time, and user is in. Reproduceable everytime.

I have seen similar issues, but no fix yet: https://github.com/manfredsteyer/angular-oauth2-oidc/issues/218

**Comment by jeroenheijmans** [comment]
You've logged this issue in my sample repo, not the library's repo: was that intentional? If it was: would you have a suggestion (or even a PR) on how to update my sample so it no longer has this problem?

You mention:

> Reproduceable everytime

That's something we all love to hear! 😄 Could you please share how _we_ can also reliably reproduce the issue? So I think that includes:

- what changes to make to my sample repository (what config, etc)
- either a minimal repro (steps) for setting up Keycloak, or a public-facing Keycloak with sample users

We'd need that to be able to look into it...

PS. You mention 218 from the library's issues list, but that doesn't seem entirely related? There most users (incl myself) mention it is _not_ reliably reproducible, and happens in _all_ browsers. (Also, that issue is closed, and mentions workarounds that are incorporated already in my sample...)

**Comment by mores** [comment]
Yes, that was my intention. No, I do not have a suggestion or PR on how to fix it.
I am just getting started with angular and can not provide much more info/insight as to the problem.

The only change I made to src/app/core/auth-config.ts was to point issuer to my keycloak.

The docs for keycloak are pretty straight forward: https://www.keycloak.org/docs/3.3/server_admin/topics/identity-broker/social/microsoft.html

I will work on setting up a public facing keycloak.

**Comment by mores** [comment]
I am testing out my public keycloak, but it does not look like angular-oauth2-oidc likes the use of a self-signed certificate. Is there a way to allow it for testing or will I have to buy a cert to test and debug this ?

**Comment by mores** [comment]
My public keycloak is available. I used LetsEncrypt to generate the certificate. I emailed you the username and password.
